export const environment = {
  production: true,
  TAG_NATURE: 'Nature',
  TAG_WILDLIFE: 'Wild Life',
  TAG_CULTURE: 'Culture',
  TAG_PEOPLE: 'People',
  TAG_CITIES: 'Cities',
  TAG_EVENTS: 'Events',
  TAG_FOOD: 'Dood',
  Nature: [
    { path: '/assets/img/Gallery/Nature/Nature_1.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_2.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_3.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_4.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_5.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_6.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_7.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_8.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_9.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_10.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_11.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_12.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_13.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_14.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_15.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_16.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_17.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_18.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_19.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_20.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_21.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_22.jpg' },
    { path: '/assets/img/Gallery/Nature/Nature_23.jpg' }
  ],

  culture: [
    { path: '/assets/img/Gallery/Culture/Culture_1.jpg' },
    { path: '/assets/img/Gallery/Culture/Culture_2.jpg' },
    { path: '/assets/img/Gallery/Culture/Culture_3.jpg' },
    { path: '/assets/img/Gallery/Culture/Culture_4.jpg' },
    { path: '/assets/img/Gallery/Culture/Culture_5.jpg' },
    { path: '/assets/img/Gallery/Culture/Culture_6.jpg' },
    { path: '/assets/img/Gallery/Culture/Culture_7.jpg' },
    { path: '/assets/img/Gallery/Culture/Culture_8.jpg' },
    { path: '/assets/img/Gallery/Culture/Culture_9.jpg' },
    { path: '/assets/img/Gallery/Culture/Culture_10.jpg' },
    { path: '/assets/img/Gallery/Culture/Culture_11.jpg' }],

  cities: [
    { path: '/assets/img/Gallery/Cities/Cities_1.jpg' },
    { path: '/assets/img/Gallery/Cities/Cities_2.jpg' },
    { path: '/assets/img/Gallery/Cities/Cities_3.jpg' },
    { path: '/assets/img/Gallery/Cities/Cities_4.jpg' },
    { path: '/assets/img/Gallery/Cities/Cities_5.jpg' },
    { path: '/assets/img/Gallery/Cities/Cities_6.jpg' },
    { path: '/assets/img/Gallery/Cities/Cities_7.jpg' },
    { path: '/assets/img/Gallery/Cities/Cities_8.jpg' },
    { path: '/assets/img/Gallery/Cities/Cities_9.jpg' },
    { path: '/assets/img/Gallery/Cities/Cities_10.jpg' },
    { path: '/assets/img/Gallery/Cities/Cities_11.jpg' }],

  people: [
    { path: '/assets/img/Gallery/People/People_1.jpg' },
    { path: '/assets/img/Gallery/People/People_2.jpg' },
    { path: '/assets/img/Gallery/People/People_3.jpg' },
    { path: '/assets/img/Gallery/People/People_4.jpg' },
    { path: '/assets/img/Gallery/People/People_5.jpg' },
    { path: '/assets/img/Gallery/People/People_6.jpg' },
    { path: '/assets/img/Gallery/People/People_7.jpg' },
    { path: '/assets/img/Gallery/People/People_8.jpg' },
    { path: '/assets/img/Gallery/People/People_9.jpg' },
    { path: '/assets/img/Gallery/People/People_10.jpg' },
    { path: '/assets/img/Gallery/People/People_11.jpg' },
    { path: '/assets/img/Gallery/People/People_12.jpg' },
    { path: '/assets/img/Gallery/People/People_13.jpg' },
    { path: '/assets/img/Gallery/People/People_14.jpg' },
    { path: '/assets/img/Gallery/People/People_15.jpg' },
    { path: '/assets/img/Gallery/People/People_16.jpg' }],

  Wild_Life: [
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_1.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_2.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_3.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_4.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_5.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_6.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_7.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_8.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_9.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_10.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_11.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_12.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_13.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_14.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_15.jpg' },
    { path: '/assets/img/Gallery/Wild_Life/Wild_Life_16.jpg' }]
};
